server:
    port: 8081
    
spring:
    application:
        name: core-api
    datasources:
        core:
            master:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:13306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnectForPools=true&allowMultiQueries=true
                max-pool-size: 5
                min-idle: 10
                user-name: user
                password: password
            slave:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:13306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnectForPools=true
                max-pool-size: 5
                min-idle: 10
                username: user
                password: password
        
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: devwoogie
            auto-offset-reset: earliest